# MySQL database connection
spring.datasource.url=jdbc:mysql://localhost:3306/banking_api
spring.datasource.username=root
spring.datasource.password=mypassword123

# Automatically create/update tables from @Entity classes
spring.jpa.hibernate.ddl-auto=create

# Show SQL queries in console
spring.jpa.show-sql=true

# Base REST API path
spring.data.rest.base-path=/api